### ISSUE TITLE
ModelUtils uses conf() instead of getLayerWiseConfiguration()

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/ImageNet-Example#11]
Line 40 here is incorrect:
https://github.com/deeplearning4j/ImageNet-Example/blob/master/src/main/java/imagenet/Utils/ModelUtils.java#L40

**Comment by nyghtowl** [comment]
This class was deprecated but has been removed to prevent further confusion. The current code lives in Dl4j under NetSaverLoader
