### ISSUE TITLE
The following artifacts could not be resolved: org.nd4j:nd4j-x86:jar:0.4-rc3.9-SNAPSHOT

### ISSUE THREAD

**Issue by ShotGunYuan** [deeplearning4j/ImageNet-Example#7]
Failed to execute goal on project Imagenet-Example: Could not resolve dependencies for project org.dl4j.imagenet.example:Imagenet-Example:jar:0.4-rc0-SNAPSHOT: The following artifacts could not be resolved: org.nd4j:nd4j-x86:jar:0.4-rc3.9-SNAPSHOT, org.deeplearning4j:deeplearning4j-core:jar:0.4-rc3.9-SNAPSHOT, org.deeplearning4j:deeplearning4j-ui:jar:0.4-rc3.9-SNAPSHOT, org.nd4j:canova-nd4j-image:jar:0.0.0.15-SNAPSHOT, org.deeplearning4j:dl4j-spark:jar:0.4-rc3.9-SNAPSHOT, org.nd4j:canova-spark:jar:0.0.0.15-SNAPSHOT: Could not find artifact org.nd4j:nd4j-x86:jar:0.4-rc3.9-SNAPSHOT -> [Help 1]

**Comment by AlexDBlack** [comment]
As noted on gitter: this repo is a work in progress. It is not currently intended for use outside of DL4J developers.
